import { z } from 'zod';

/**
 * The structured summary contract.
 *
 * This schema is the boundary between "what a language model said" and "what
 * this service is willing to call a summary". Model output is untrusted input:
 * it is parsed, not cast. Anything that does not fit is rejected outright
 * rather than patched up, because a half-valid summary of a medical document is
 * worse than no summary — it looks authoritative and is wrong in places nobody
 * can see.
 *
 * The shape mirrors `DocumentSummary` in the mobile app's `src/types/domain.ts`
 * (see P1-02). The two are kept in step by the written contract in
 * docs/architecture/phase-1.md, not by a shared import — backend/README.md
 * explains why the packages stay separate.
 */

/** Matches `DoctorCategory` in the app. */
export const DOCTOR_CATEGORIES = [
  'general_physician',
  'cardiologist',
  'endocrinologist',
  'nephrologist',
  'orthopaedic',
  'ophthalmologist',
  'pulmonologist',
  'neurologist',
  'gastroenterologist',
  'dermatologist',
] as const;

/** Matches `FollowUpKind` in the app. */
export const FOLLOW_UP_KINDS = [
  'doctor_visit',
  'lab_test',
  'medicine_refill',
  'vaccination',
  'physiotherapy',
  'other',
] as const;

export const FINDING_SEVERITIES = ['normal', 'watch', 'attention'] as const;

const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'must be an ISO calendar date');

/**
 * A page reference.
 *
 * `page` is bounded at parse time by the orchestrator, which knows how many
 * pages the document actually has — see `SourceConsistencyValidator`. Here it
 * only has to be a positive integer.
 */
const sourceReference = z.object({
  page: z.number().int().positive(),
  /**
   * Optional and cut from *redacted* text. The validator re-checks it through
   * the leakage gate before it is allowed out (ADR-002 § "Source snippets").
   */
  textSnippet: z.string().max(200).optional(),
});

const finding = z.object({
  label: z.string().min(1).max(200),
  value: z.string().min(1).max(200),
  unit: z.string().max(50).nullable().optional(),
  referenceRange: z.string().max(200).nullable(),
  severity: z.enum(FINDING_SEVERITIES),
  plainLanguage: z.string().min(1).max(600),
  sources: z.array(sourceReference).default([]),
});

const medicine = z.object({
  name: z.string().min(1).max(200),
  dosage: z.string().max(120),
  frequency: z.string().max(200),
  purpose: z.string().max(300),
  duration: z.string().max(120).nullable().optional(),
  sources: z.array(sourceReference).default([]),
});

const explicitFollowUp = z.object({
  title: z.string().min(1).max(200),
  /** `null` when the document gives an interval but no resolvable date. */
  date: isoDate.nullable(),
  kind: z.enum(FOLLOW_UP_KINDS),
  source: sourceReference,
  confidence: z.number().min(0).max(1),
});

const uncertainty = z.object({
  message: z.string().min(1).max(400),
  sourcePage: z.number().int().positive().nullable(),
});

export const summarySchema = z.object({
  overview: z.string().min(1).max(600),
  plainLanguageSummary: z.string().min(1).max(2000),
  findings: z.array(finding).max(60),
  medicines: z.array(medicine).max(40),
  /** Transcribed from the document. Never generated — see the system prompt. */
  instructions: z.array(z.string().min(1).max(500)).max(30),
  recommendedDoctorCategory: z.enum(DOCTOR_CATEGORIES),
  /** Generated by the model, and labelled as such in the UI. */
  questionsForDoctor: z.array(z.string().min(1).max(400)).max(20),
  confidence: z.number().min(0).max(1),
  detectedDocumentDate: isoDate.nullable().optional(),
  explicitFollowUps: z.array(explicitFollowUp).max(20).default([]),
  uncertainties: z.array(uncertainty).max(30).default([]),
});

export type StructuredSummary = z.infer<typeof summarySchema>;
export type SummaryFinding = z.infer<typeof finding>;
export type SummaryMedicine = z.infer<typeof medicine>;
export type SummaryExplicitFollowUp = z.infer<typeof explicitFollowUp>;
export type SummarySourceReference = z.infer<typeof sourceReference>;

/**
 * JSON Schema sent to the provider so it constrains its own output.
 *
 * Hand-written rather than generated: it is part of the request payload, and a
 * generator's incidental changes would silently alter what the model is asked
 * for. Kept deliberately small — the zod schema above is the authority, and
 * this is a hint to the model, not the thing that makes output safe.
 */
export const SUMMARY_JSON_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: [
    'overview',
    'plainLanguageSummary',
    'findings',
    'medicines',
    'instructions',
    'recommendedDoctorCategory',
    'questionsForDoctor',
    'confidence',
  ],
  properties: {
    overview: { type: 'string' },
    plainLanguageSummary: { type: 'string' },
    findings: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['label', 'value', 'referenceRange', 'severity', 'plainLanguage', 'sources'],
        properties: {
          label: { type: 'string' },
          value: { type: 'string' },
          unit: { type: ['string', 'null'] },
          referenceRange: { type: ['string', 'null'] },
          severity: { type: 'string', enum: FINDING_SEVERITIES },
          plainLanguage: { type: 'string' },
          sources: { type: 'array', items: { $ref: '#/$defs/source' } },
        },
      },
    },
    medicines: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['name', 'dosage', 'frequency', 'purpose', 'sources'],
        properties: {
          name: { type: 'string' },
          dosage: { type: 'string' },
          frequency: { type: 'string' },
          purpose: { type: 'string' },
          duration: { type: ['string', 'null'] },
          sources: { type: 'array', items: { $ref: '#/$defs/source' } },
        },
      },
    },
    instructions: { type: 'array', items: { type: 'string' } },
    recommendedDoctorCategory: { type: 'string', enum: DOCTOR_CATEGORIES },
    questionsForDoctor: { type: 'array', items: { type: 'string' } },
    confidence: { type: 'number', minimum: 0, maximum: 1 },
    detectedDocumentDate: { type: ['string', 'null'] },
    explicitFollowUps: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['title', 'date', 'kind', 'source', 'confidence'],
        properties: {
          title: { type: 'string' },
          date: { type: ['string', 'null'] },
          kind: { type: 'string', enum: FOLLOW_UP_KINDS },
          source: { $ref: '#/$defs/source' },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
        },
      },
    },
    uncertainties: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['message', 'sourcePage'],
        properties: {
          message: { type: 'string' },
          sourcePage: { type: ['integer', 'null'] },
        },
      },
    },
  },
  $defs: {
    source: {
      type: 'object',
      additionalProperties: false,
      required: ['page'],
      properties: {
        page: { type: 'integer', minimum: 1 },
        textSnippet: { type: 'string' },
      },
    },
  },
} as const;
