import { encodePng, type GreyscaleBitmap } from './images.js';

/**
 * Renders text into a PNG so an OCR test has something genuine to read.
 *
 * A 5×7 bitmap font, scaled up. It exists because the alternative — committing
 * a photograph of a document — is exactly what Phase 1 forbids, and because a
 * generated image can be regenerated by anyone running the suite. Glyph shapes
 * are blocky; see the OCR test for what that costs in recognition accuracy.
 */

// 5 columns × 7 rows per glyph. '#' is ink.
const FONT: Record<string, string[]> = {
  A: ['..#..', '.#.#.', '#...#', '#####', '#...#', '#...#', '#...#'],
  B: ['####.', '#...#', '#...#', '####.', '#...#', '#...#', '####.'],
  C: ['.####', '#....', '#....', '#....', '#....', '#....', '.####'],
  D: ['####.', '#...#', '#...#', '#...#', '#...#', '#...#', '####.'],
  E: ['#####', '#....', '####.', '#....', '#....', '#....', '#####'],
  F: ['#####', '#....', '####.', '#....', '#....', '#....', '#....'],
  G: ['.####', '#....', '#....', '#..##', '#...#', '#...#', '.####'],
  H: ['#...#', '#...#', '#####', '#...#', '#...#', '#...#', '#...#'],
  I: ['#####', '..#..', '..#..', '..#..', '..#..', '..#..', '#####'],
  J: ['#####', '...#.', '...#.', '...#.', '...#.', '#..#.', '.##..'],
  K: ['#...#', '#..#.', '#.#..', '##...', '#.#..', '#..#.', '#...#'],
  L: ['#....', '#....', '#....', '#....', '#....', '#....', '#####'],
  M: ['#...#', '##.##', '#.#.#', '#...#', '#...#', '#...#', '#...#'],
  N: ['#...#', '##..#', '#.#.#', '#..##', '#...#', '#...#', '#...#'],
  O: ['.###.', '#...#', '#...#', '#...#', '#...#', '#...#', '.###.'],
  P: ['####.', '#...#', '#...#', '####.', '#....', '#....', '#....'],
  Q: ['.###.', '#...#', '#...#', '#...#', '#.#.#', '#..#.', '.##.#'],
  R: ['####.', '#...#', '#...#', '####.', '#.#..', '#..#.', '#...#'],
  S: ['.####', '#....', '#....', '.###.', '....#', '....#', '####.'],
  T: ['#####', '..#..', '..#..', '..#..', '..#..', '..#..', '..#..'],
  U: ['#...#', '#...#', '#...#', '#...#', '#...#', '#...#', '.###.'],
  V: ['#...#', '#...#', '#...#', '#...#', '#...#', '.#.#.', '..#..'],
  W: ['#...#', '#...#', '#...#', '#...#', '#.#.#', '##.##', '#...#'],
  X: ['#...#', '#...#', '.#.#.', '..#..', '.#.#.', '#...#', '#...#'],
  Y: ['#...#', '#...#', '.#.#.', '..#..', '..#..', '..#..', '..#..'],
  Z: ['#####', '....#', '...#.', '..#..', '.#...', '#....', '#####'],
  '0': ['.###.', '#...#', '#..##', '#.#.#', '##..#', '#...#', '.###.'],
  '1': ['..#..', '.##..', '..#..', '..#..', '..#..', '..#..', '#####'],
  '2': ['.###.', '#...#', '....#', '...#.', '..#..', '.#...', '#####'],
  '3': ['####.', '....#', '....#', '.###.', '....#', '....#', '####.'],
  '4': ['...#.', '..##.', '.#.#.', '#..#.', '#####', '...#.', '...#.'],
  '5': ['#####', '#....', '####.', '....#', '....#', '#...#', '.###.'],
  '6': ['.###.', '#....', '#....', '####.', '#...#', '#...#', '.###.'],
  '7': ['#####', '....#', '...#.', '..#..', '.#...', '.#...', '.#...'],
  '8': ['.###.', '#...#', '#...#', '.###.', '#...#', '#...#', '.###.'],
  '9': ['.###.', '#...#', '#...#', '.####', '....#', '....#', '.###.'],
  '.': ['.....', '.....', '.....', '.....', '.....', '.##..', '.##..'],
  ',': ['.....', '.....', '.....', '.....', '.##..', '.##..', '.#...'],
  ':': ['.....', '.##..', '.##..', '.....', '.##..', '.##..', '.....'],
  '-': ['.....', '.....', '.....', '#####', '.....', '.....', '.....'],
  '/': ['....#', '...#.', '...#.', '..#..', '.#...', '.#...', '#....'],
  '%': ['##..#', '##.#.', '...#.', '..#..', '.#...', '.#.##', '#..##'],
  '(': ['..##.', '.#...', '#....', '#....', '#....', '.#...', '..##.'],
  ')': ['.##..', '...#.', '....#', '....#', '....#', '...#.', '.##..'],
  '+': ['.....', '..#..', '..#..', '#####', '..#..', '..#..', '.....'],
  '#': ['.#.#.', '#####', '.#.#.', '.#.#.', '#####', '.#.#.', '.....'],
  '@': ['.###.', '#...#', '#.###', '#.#.#', '#.###', '#....', '.###.'],
  ' ': ['.....', '.....', '.....', '.....', '.....', '.....', '.....'],
};

const GLYPH_WIDTH = 5;
const GLYPH_HEIGHT = 7;

export interface RenderTextOptions {
  /** Pixels per font pixel. 8 gives a ~56px cap height, which OCR handles. */
  scale?: number;
  /** Blank pixels around the text block. */
  margin?: number;
  /** Blank font-pixels between glyphs and between lines. */
  letterSpacing?: number;
  lineSpacing?: number;
}

/**
 * Renders uppercase text. Lowercase is folded to uppercase — the font has no
 * lowercase glyphs, and a missing glyph would silently become a space.
 */
export const renderTextBitmap = (
  lines: string[],
  options: RenderTextOptions = {},
): GreyscaleBitmap => {
  const scale = options.scale ?? 8;
  const margin = options.margin ?? 24;
  const letterSpacing = options.letterSpacing ?? 1;
  const lineSpacing = options.lineSpacing ?? 4;

  const upper = lines.map((line) => line.toUpperCase());
  const columns = Math.max(...upper.map((line) => line.length), 1);

  const textWidth = columns * (GLYPH_WIDTH + letterSpacing) - letterSpacing;
  const textHeight = upper.length * (GLYPH_HEIGHT + lineSpacing) - lineSpacing;

  const width = textWidth * scale + margin * 2;
  const height = textHeight * scale + margin * 2;
  const pixels = new Uint8Array(width * height).fill(255);

  const paint = (x: number, y: number): void => {
    for (let dy = 0; dy < scale; dy += 1) {
      for (let dx = 0; dx < scale; dx += 1) {
        const px = margin + x * scale + dx;
        const py = margin + y * scale + dy;
        if (px < width && py < height) {
          pixels[py * width + px] = 0;
        }
      }
    }
  };

  upper.forEach((line, lineIndex) => {
    const originY = lineIndex * (GLYPH_HEIGHT + lineSpacing);

    [...line].forEach((character, columnIndex) => {
      const glyph = FONT[character] ?? FONT[' ']!;
      const originX = columnIndex * (GLYPH_WIDTH + letterSpacing);

      glyph.forEach((row, rowIndex) => {
        [...row].forEach((cell, cellIndex) => {
          if (cell === '#') {
            paint(originX + cellIndex, originY + rowIndex);
          }
        });
      });
    });
  });

  return { width, height, pixels };
};

/** Convenience: text straight to PNG bytes. */
export const renderTextPng = (lines: string[], options: RenderTextOptions = {}): Buffer =>
  encodePng(renderTextBitmap(lines, options));

/** Characters this font can draw. Anything else renders blank. */
export const SUPPORTED_CHARACTERS = Object.keys(FONT);
